apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-clusterrole
rules:
  - apiGroups: ["workshop.io"]
    resources: ["clusters"]
    verbs: ["get", "watch", "list", "create", "delete"]