apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: kubeapi-inspector-workshop
  labels:
    app: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.4.13
        command:
        - etcd
        - --advertise-client-urls=https://0.0.0.0:2379
        - --listen-client-urls=https://0.0.0.0:2379
        - --cert-file=/etc/etcd/certs/server.crt
        - --key-file=/etc/etcd/certs/server.key
        - --client-cert-auth
        - --trusted-ca-file=/etc/etcd/certs/ca.crt
        - --data-dir=/var/lib/etcd
        ports:
        - containerPort: 2379
          name: client
        volumeMounts:
        - name: etcd-certs
          mountPath: /etc/etcd/certs
          readOnly: true
        - name: etcd-data
          mountPath: /var/lib/etcd
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
      volumes:
      - name: etcd-certs
        secret:
          secretName: etcd-certs
          defaultMode: 0400
      - name: etcd-data
        emptyDir: {} 