apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: kubeapi-inspector-workshop
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: client
    targetPort: 2379
  selector:
    app: etcd 